config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fortunes
  root to: "home#index"
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  belongs_to :user

  validates :copy, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :encrypted_password, :reset_password_token, :reset_password_sent_at
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :fortunes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  before_filter :authorize, :except => [:index, :show]


  def index
    @fortune = Fortune.limit(1).order("RANDOM()").first
    if user_signed_in?
      @fortunes = Fortune.order(:created_at);
    end
  end
  
  def new
    @fortune = Fortune.new
  end  

  def create
    @fortune = Fortune.new(fortune_params)
    if @fortune.save
      redirect_to fortunes_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @fortune = Fortune.find params[:id]
    render :action => 'new'
  end

  def update
  	@fortune = Fortune.find params[:id]
  	if(@fortune.update_attributes params[:post])
  	  redirect_to fortunes_path
  	else
  		render :action => :edit
  	end
  end

  def destroy
  	@fortune = Fortune.find params[:id]
  	@fortune.destroy
  	redirect_to fortunes_path
  end

  def show
    @fortune = Fortune.find params[:id]
  end

  protected
    def authorize
      redirect_to new_user_session_path and return unless user_signed_in?
    end

  private
    def fortune_params
    	params.require(:fortune).permit(:copy, :user_id)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @fortune = Fortune.limit(1).order("RANDOM()").first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/views/fortunes/index.html.erb
<%= render "shared/fortune", :fortune => @fortune %>


<% if(current_user) %>
<div class="wrapper row">
<h2>List of fortunes</h2>
<ul class="my fortunes">  	
<%  	@fortunes.each do | f | %>
  <li><%= link_to f.copy, edit_fortune_path(f) %> <%= button_to 'delete', {:controller => :fortunes, :action => 'destroy', :id => f.id }, :method => :delete %></li>
<% end %>
</ul>
</div>
<%  end  %>

app/views/fortunes/new.html.erb
<div class="edit form">
<%= form_for :fortune, url: fortunes_path do |f| %>
   

  <div class="field row">
    <%= f.hidden_field(:user_id, value: current_user.id) %>
    <%= f.label :copy,  "Fortune content goes in the field" %><br>
    <%= f.text_area(:copy, cols: 100, rows: 10) %>
  </div>
 
  <div class="field row">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/fortunes/show.html.erb
<%= render "shared/fortune", :fortune => @fortune %>

app/views/home/index.html.erb
<%= render "shared/fortune", :fortune => @fortune %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Fufortune</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="FU.....Fortune">
<meta property="og:title" content="Fu Fortune" />
<meta property="og:type" content="fun" />
<meta property="og:image" content="http://fufortune.herokuapp.com/images/cookie.svg" />
<meta property="og:url" content="http://fufortune.herokuapp.com" />
<meta property="og:site_name" content="Fufortune" />
<link href='https://fonts.googleapis.com/css?family=Laila:600,300' rel='stylesheet'>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body id="fufortune">

  <div class="clearfix center" id="site-wrap">
    
    <header class="site-header px-responsive">
      <div class="mt2 wrap py2 clearfix">
        <h1><a href="/">Fu Fortune</a></h1>
      </div>


      <div class="clearfix">
        <div class="col-6 pb4 mx-auto cookie">
          <a href="/"><img class="fit" src="/images/cookie.svg" alt="This the fortune cookie"></a>
        </div>
      </div>

    </header>


    <% if user_signed_in? %>
    <div class="logged in">
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
    <% end %>    

    <% if notice %>
      <p class="alert alert-success row"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger row"><%= alert %></p>
    <% end %>    

    <%= yield %>
    <div class="addthis_inline_share_toolbox py2"></div>
    <div class="clearifx py2">
      <div class="col-6 sm-col-10 mx-auto permalink" id="link">
      </div>
    </div>

    <footer></footer>

  </div>

<%= render 'shared/ganalytics' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-52fc6baf5c257a1d"></script>
<script type="text/javascript">
  var fortune = document.getElementById('the-fortune');
  var addthis_config = addthis_config||{};
  addthis_config.data_track_clickback = false;
  addthis_config.data_track_addressbar = false;
  var addthis_share = {
    url: 'http://fufortune.wtf/fortunes/' + fortune.getAttribute('data-id'),
    title: "Fu Fortune # " + fortune.getAttribute('data-id'),
  }

  var link = document.getElementById('link');
  link.innerHTML= '<a href="http://fufortune.wtf/fortunes/'+fortune.getAttribute('data-id')+'">http://fufortune.wtf/fortunes/'+fortune.getAttribute('data-id') +'</a>';
  
  var rGradient = Math.floor(Math.random() * 3) + 1;
  var root = document.getElementById( 'site-wrap' ); 
  root.classList.add('grd-'+rGradient );


</script>
</body>
</html>

app/views/shared/_fortune.html.erb
<div class="clearfix ">
  <div class="col-8 px2 mb3 mx-auto">
    <div id="the-fortune" class="fortune p4" data-id="<%= fortune.id %>"><%= fortune.copy %></div>
  </div>
</div>

app/views/shared/_ganalytics.html.erb
<% if ENV['GA_ACCOUNT_ID'] %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GA_ACCOUNT_ID'] %>', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>